### ISSUE TITLE
Problem with JS Test from Postman

### ISSUE THREAD

**Issue by amartinezmena** [poynt/postman-runner#10]
When i try to ecute a postman collection with test:

2018-11-22 13:11:13.577  INFO c.p.p.PostmanRequestRunner     :  [587ms]
org.mozilla.javascript.EcmaError: TypeError: Cannot call method "json" of undefined (---------------------> POSTMAN test#1)
	at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3785)
	at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3763)
	at org.mozilla.javascript.ScriptRuntime.typeError(ScriptRuntime.java:3791)
	at org.mozilla.javascript.ScriptRuntime.typeError2(ScriptRuntime.java:3810)
	at org.mozilla.javascript.ScriptRuntime.undefCallError(ScriptRuntime.java:3829)
	at org.mozilla.javascript.ScriptRuntime.getPropFunctionAndThisHelper(ScriptRuntime.java:2334)
	at org.mozilla.javascript.ScriptRuntime.getPropFunctionAndThis(ScriptRuntime.java:2327)

The test is:

var jsonData = pm.response.json();

pm.test("Test idOperacion", function () {
    pm.expect(jsonData.idOperacion).to.eql("OPMMMU01");
});

**Comment by vchau** [comment]
Hi @amartinezmena ,
Unfortunately, we don't currently yet support the new `pm` global variable that was introduced in Postman 2.x.  The current implementation only support the older 1.x style test by parsing teh `responseBody` variable, which is still suppported by the Postman 2.x client.  For example:

```
tests["Status code is 200"] = responseCode.code === 200;

var data = JSON.parse(responseBody);

tests["Check Foo In Body"] = data.foo === "FOO";
postman.setEnvironmentVariable("foo", data.foo);
```

You can see the details in the Postman documentation here https://learning.getpostman.com/docs/postman/scripts/postman_sandbox/#requestresponse-related-properties

**Comment by Joby81** [comment]
did you resolved the pm issue ? if not i am facing an issue for 
postman.setGlobalVariable("access_token", data.headers["postman-token"]);

["postman-token"] is not working . Please let me know how can we do that ?

**Comment by ninaHerpertz** [comment]
We are facing the same issue. The request name (request.name) is not available in postman anymore but the alternative pm.info.requestName is not available in the library. 
@Joby81: Did you create a fork of the project where I can take a look at the changes you have made so far?

**Comment by Joby81** [comment]
Hi 

> We are facing the same issue. The request name (request.name) is not available in postman anymore but the alternative pm.info.requestName is not available in the library.
> @Joby81: Did you create a fork of the project where I can take a look at the changes you have made so far?

I used this project for something else ( Generating Postman Scripts from Swagger UI )

But The solution would be 
Step 1 : Create a class which is for pm ( in my case i created PmApi.java)
public class PmApi {
	public Response response;
	public EnviornmentStore globals;
	public EnviornmentStore environment;
}
public class Response {
	public To to;
	public PostmanHttpResponse responseBody;
} 
And include the Have object in the same format ( I kept public to get it accessed)  ( I hope you got the logic) 
Step 2 : Include PmApi object in PostmanJsVariables ( go to injectJsVariablesToScope method and add the pm object ) 
		ScriptableObject.putProperty(scope, "pm", new PmApi());

I hope the rest is very easy to extend the runner. Please let me know incase if you face any issues. 

Regards, 
Joby

**Comment by Guha5277** [comment]
@vchau your example didn't wotk :(

I was copy your test example into postman:
`tests["Status code is 200"] = responseCode.code === 200;

var data = JSON.parse(responseBody);

tests["Check Foo In Body"] = data.foo === "FOO";
postman.setEnvironmentVariable("foo", data.foo);`

Make request to a postman-echo.com/post with post body:
`{
  "foo": "FOO"
}`

And all works fine into Postman, but when i export collections to json file, import to my java project:
`        PostmanRunResult result = cr.runCollection(
                "tests/PostmanEcho.postman_collection.json",
                "tests/LocalOctoprint.postman_environment.json",
                "Base", false);`

 and run, logs are:
`=====FAILED TO EVALUATE TEST AGAINST SERVER RESPONSE======`

As result:
`Total Requests = 1
Failed Requests = 1
Total Tests = 0
Failed Tests = 0
Failed Request Names: [Base.Post Echo]
Failed Test Names: []`

**Comment by agileselenium** [comment]
> Hi
> 
> > We are facing the same issue. The request name (request.name) is not available in postman anymore but the alternative pm.info.requestName is not available in the library.
> > @Joby81: Did you create a fork of the project where I can take a look at the changes you have made so far?
> 
> I used this project for something else ( Generating Postman Scripts from Swagger UI )
> 
> But The solution would be Step 1 : Create a class which is for pm ( in my case i created PmApi.java) public class PmApi { public Response response; public EnviornmentStore globals; public EnviornmentStore environment; } public class Response { public To to; public PostmanHttpResponse responseBody; } And include the Have object in the same format ( I kept public to get it accessed) ( I hope you got the logic) Step 2 : Include PmApi object in PostmanJsVariables ( go to injectJsVariablesToScope method and add the pm object ) ScriptableObject.putProperty(scope, "pm", new PmApi());
> 
> I hope the rest is very easy to extend the runner. Please let me know incase if you face any issues.
> 
> Regards, Joby

Hi Joby,

Can you please provide a sample project for reference? I'm unable to make it work with pm object.

Regards,
Shankar

**Comment by agileselenium** [comment]
> Hi
> 
> > We are facing the same issue. The request name (request.name) is not available in postman anymore but the alternative pm.info.requestName is not available in the library.
> > @Joby81: Did you create a fork of the project where I can take a look at the changes you have made so far?
> 
> I used this project for something else ( Generating Postman Scripts from Swagger UI )
> 
> But The solution would be Step 1 : Create a class which is for pm ( in my case i created PmApi.java) public class PmApi { public Response response; public EnviornmentStore globals; public EnviornmentStore environment; } public class Response { public To to; public PostmanHttpResponse responseBody; } And include the Have object in the same format ( I kept public to get it accessed) ( I hope you got the logic) Step 2 : Include PmApi object in PostmanJsVariables ( go to injectJsVariablesToScope method and add the pm object ) ScriptableObject.putProperty(scope, "pm", new PmApi());
> 
> I hope the rest is very easy to extend the runner. Please let me know incase if you face any issues.
> 
> Regards, Joby

@Joby81 can you please share a sample project with the pm issue fix.

**Comment by shubhDcoder** [comment]
Any update on this issue ?
