### ISSUE TITLE
Throwing java.lang.NullPointerException

### ISSUE THREAD

**Issue by amnoman** [poynt/postman-runner#2]
Collection Type: Collection V2.1
[PostmanFramework.zip](https://github.com/poynt/postman-runner/files/1487946/PostmanFramework.zip)

      <dependency>
    <groupId>co.poynt.postman.runner</groupId>
    <artifactId>postman-runner</artifactId>
    <version>1.0.9</version>
</dependency>

Exception in thread "main" java.lang.NullPointerException
	at co.poynt.postman.model.PostmanCollection.init(PostmanCollection.java:20)
	at co.poynt.postman.PostmanCollectionRunner.runCollection(PostmanCollectionRunner.java:57)
	at com.toyotaconnected.dcm_postman.CollectionRunner.main(CollectionRunner.java:29)

**Comment by StatKatsaros** [comment]
I am facing the same error.

**Comment by rishikeshs** [comment]
Con anyone help me to run this code? I am just export Postman collection V1 and paste it in java/src/resources folder. I just pass collection name, my postman doesn't have any environment variable, folder name and other parameters. I am new to this environment. I have also query about version for PostmanRunner artifact id.

**Comment by vchau** [comment]
Please use postman-runner 2.0.2
